language: go

sudo: required

servics:
        - docker

go:
        - 1.10.x
        - 1.9.x

before_script:
        - go get github.com/golang/lint/golint

script:
        - make validate
        - make build
        - make test
