language: go

sudo: required

servics:
        - docker

go:
        - tip
        - 1.12.x

before_install:
        - sudo add-apt-repository ppa:duggan/bats --yes
        - sudo apt-get update -qq
        - sudo apt-get install -qq bats

before_script:
        - go get github.com/golang/lint/golint

script:
        - make validate
        - make build
        - make test
